version: "3.8"
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bullseye
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity
    # ports:
    #   - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../db:/docker-entrypoint-initdb.d/
      - ./data:/var/lib/mysql
